name: CI

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: Name of the docker image
        required: true
      image_version:
        description: Version of the docker image

permissions:
  id-token: write 
  contents: read  

jobs:
  tag:
    runs-on: ubuntu-latest
    name: Build
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ACR login
        run: az acr login --name ${{ secrets.AZURE_ACR_REGISTRY_NAME }}

      - id: metadata
        name: Compute Metadata
        run: |
          echo "current_date=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_OUTPUT

      - id: docker_image
        name: Build Image
        uses: docker/build-push-action@v5
        with:
          context: "."
          no-cache: true
          push: true
          tags: |
            ${{ format('{0}.azurecr.io/{1}:latest', secrets.AZURE_ACR_REGISTRY_NAME, inputs.image_name) }}
            ${{ inputs.image_version && format('{0}.azurecr.io/{1}:{2}', secrets.AZURE_ACR_REGISTRY_NAME, inputs.image_name, inputs.image_version) }}
          platforms: linux/amd64
          labels: |
            org.opencontainers.image.title=${{ inputs.image_name }}
            org.opencontainers.image.url=${{ github.repositoryUrl }}
            org.opencontainers.image.created=${{ steps.metadata.outputs.current_date }}
            org.opencontainers.image.revision=${{ github.sha }}
