name: CI

on:
  workflow_dispatch:
    inputs:
      image_version:
        description: Version of the docker image (Optional)

jobs:
  tag:
    runs-on: ubuntu-latest
    name: Build
    permissions:
      contents: read
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.AZURE_ACR_REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_ACR_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_ACR_REGISTRY_TOKEN }}

      - id: metadata
        name: Compute Metadata
        run: |
          echo "current_date=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_OUTPUT

      - id: docker_image
        name: Build Image
        uses: docker/build-push-action@v5
        with:
          context: "app"
          no-cache: true
          push: true
          tags: |
            ${{ secrets.AZURE_ACR_REGISTRY_LOGIN_SERVER }}/${{ secrets.AZURE_ACR_REGISTRY_USERNAME }}:latest
            ${{ inputs.image_version && format('{0}/{1}:{2}', secrets.AZURE_ACR_REGISTRY_LOGIN_SERVER, secrets.AZURE_ACR_REGISTRY_USERNAME, inputs.image_version) }}
          platforms: linux/amd64
          labels: |
            org.opencontainers.image.name=${{ secrets.AZURE_ACR_REGISTRY_LOGIN_SERVER }}/${{ secrets.AZURE_ACR_REGISTRY_USERNAME }}
            org.opencontainers.image.url=${{ github.repositoryUrl }}
            org.opencontainers.image.created=${{ steps.metadata.outputs.current_date }}
            org.opencontainers.image.revision=${{ github.sha }}
