name: CI

on:
  workflow_dispatch:

permissions:
  id-token: write 
  contents: read  

jobs:
  tag:
    runs-on: ubuntu-latest
    name: Build
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Run az commands'
        run: |
            az account show
            az group list
